### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by edin-m** [shi-yan/Swiftly#1]
Hi, I was recently disappointed with the availability of HTTP server libraries for Qt.

This one seems nice. I've managed to run it in Windows and I had to comment out some unneeded code. 

Is this library still active, is it stable?
What are unsupported features?

My use case is a simple HTTP communication between applications. No advanced HTTP features needed (except maybe for SSL).

**Comment by shi-yan** [comment]
the first version is usable. I was working on a second version, which won't be based on QT though. (vanilla c++ , co-routine and Io_uring )
